#ifndef _MVL_VERSION_HEADER
#define _MVL_VERSION_HEADER

#ifdef _MVL_DEBUG
	#define MVL_VERSION_IDENTIFICATION	"MVLD_1.0.0"
#else
	#define MVL_VERSION_IDENTIFICATION	"MVLR_1.0.0"
#endif

#endif // _MVL_VERSION_HEADER