#ifndef _OBJECT_IDENTIFICATION_HEADER_
#define _OBJECT_IDENTIFICATION_HEADER_

typedef enum _EMVL_OBJECT_ID
{
	EMVL_UNDEFINED_OBJECT	= -1,

	EMVL_WORKSPACE_OBJECT_ID	= 0,
	EMVL_IMAGE_OBJECT_ID,
	EMVL_GRADIENT_ANALIZER_OBJECT_ID,
	EMVL_SETTINGS_OBJECT_ID,
	EMVL_ERROR_MANAGER_OBJECT_ID,
	EMVL_RESULT_OBJECT_ID,

	// Last one
	EMVL_NUMBER_OF_OBJECT_ID

} EMVL_OBJECT_ID;


#endif //_OBJECT_IDENTIFICATION_HEADER_